CONNECTALDIR?=/opt/connectal
S2H_INTERFACES = PaxosRequest:Paxos.request
H2S_INTERFACES = Paxos:PaxosIndication

BSVFILES = Paxos.bsv
CPPFILES = testpaxos.cpp

include $(CONNECTALDIR)/Makefile.connectal
